### PR TITLE
This fixes a crash on Android OS 12...

### PR DESCRIPTION
**Pull request by dspells**
On my Pixel Pro 6 with Android OS 12 starting a scan crashes every time without this change. I'm not sure why this hasn't been found and fixed before now.

### CODE REVIEW

**Comment by sophisticode** [comment]
It sounds strange to me that you need permission BLUETOOTH_CONNECT to start a scan.
Does it also happen with the example app of this plugin?
Do you see the dialog where the user is asked to grant access to nearby devices?
Could you please post the crash log when running without your change.

**Comment by dspells** [comment]
I believe that it actually happens when you access one of the fields in the ScanResult. I will get the crash log tomorrow. It happens every time for me.

**Comment by daniel-possienke** [comment]
I've got the same issue with a S21 with android 12. As soon as I'm scanning for new devices the app crashes with the following error message: 
`java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@caded90: AdapterService getRemoteName`

I've tested your PR and the issue seems to be fixed with that.

**Comment by dspells** [comment]
`E/AndroidRuntime(23721): Process: com.apcon.intellaviewmobile, PID: 23721
E/AndroidRuntime(23721): java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@7a60231: AdapterService getRemoteName
E/AndroidRuntime(23721): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
E/AndroidRuntime(23721): 	at android.os.Parcel.createException(Parcel.java:2409)
E/AndroidRuntime(23721): 	at android.os.Parcel.readException(Parcel.java:2392)
E/AndroidRuntime(23721): 	at android.os.Parcel.readException(Parcel.java:2334)
E/AndroidRuntime(23721): 	at android.bluetooth.IBluetooth$Stub$Proxy.getRemoteName(IBluetooth.java:3395)
E/AndroidRuntime(23721): 	at android.bluetooth.BluetoothDevice.getName(BluetoothDevice.java:1273)
E/AndroidRuntime(23721): 	at com.boskokg.flutter_blue_plus.ProtoMaker.from(ProtoMaker.java:103)
E/AndroidRuntime(23721): 	at com.boskokg.flutter_blue_plus.ProtoMaker.from(ProtoMaker.java:49)
E/AndroidRuntime(23721): 	at com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin$2.onScanResult(FlutterBluePlusPlugin.java:814)
E/AndroidRuntime(23721): 	at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run(BluetoothLeScanner.java:531)
E/AndroidRuntime(23721): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(23721): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(23721): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(23721): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(23721): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
E/AndroidRuntime(23721): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23721): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(23721): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
`

**Comment by dspells** [comment]
Apparently if you need to get the name of the BluetoothDevice on OS 12 you need android.permission.BLUETOOTH_CONNECT permission.

If you read this https://developer.android.com/guide/topics/connectivity/bluetooth/permissions
It's not obvious that you need to request BLUETOOTH_CONNECT permissions.

However, the Exception is pretty clear. It tells you that the permission is required.

I would think that you could get the name from the advertisement data instead of querying the device (assuming that localName is not empty). But I don't know what the most correct answer is here.

**Comment by ekuleshov** [comment]
This and other Android 12 stuff been brought up in https://github.com/boskokg/flutter_blue_plus/issues/7

Should be all fixed in this fork https://github.com/espresso3389/flutter_blue/commits/master
It is unfortunate @[espresso3389](https://github.com/espresso3389) could not contribute his PR into this new project.

**Pull request merged**
