### PR TITLE
Include Proguard rule in README.md

### PR DESCRIPTION
**Pull request by shubhamsinghmutualmobile**
This PR adds a simple entry in the `README.md` file to let all new and existing users of this library know about the Proguard rule they need to add to their `proguard-rules.pro` file in order to avoid seeing obfuscation issues in their release builds.

### CODE REVIEW

**Comment by chipweinberger** [comment]
This error does not look like it comes from FlutterBluePlus.

"Field devices_ for c.d.a.m not found." 

I don't know of a "devices_" field.

**Comment by shubhamsinghmutualmobile** [comment]
Good observation @chipweinberger 
It was bad on my part, I copied the error message from an [issue](https://github.com/pauldemarco/flutter_blue/issues/855) on the `flutter_blue` repo instead of `flutter_blue_plus` ([this](https://github.com/boskokg/flutter_blue_plus/issues/15))

I will update this and request a review again.
Thanks for catching this 👍

**Comment by shubhamsinghmutualmobile** [comment]
I was also wondering if I should create another build that adds the proguard file in the library itself instead of asking the user to do so 🤔 Could there be a downside to that?

**Comment by chipweinberger** [comment]
if that is possible sure. please test it!

**Comment by shubhamsinghmutualmobile** [comment]
> if that is possible sure. please test it!

I'll surely try and work on it. In the meanwhile, if this PR looks okay, could you approve and merge it @chipweinberger?

**Comment by chipweinberger** [comment]
It is nearly good enough! 

But I would want the example error to be a real error! 

Have you actually ever needed this proguard rule after we remove Protobuf? What errors have you hit?

**Comment by shubhamsinghmutualmobile** [comment]
This is a real error, it comes from one of your existing issues: https://github.com/boskokg/flutter_blue_plus/issues/15
And I'm not sure on which version you removed Protobuf, but I'm facing this same issue with version 1.5.2 and this is the error I see:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Field state_ for c1.u not found. Known fields are [private int c1.u.v, private static final c1.u c1.u.w, private static volatile com.google.protobuf.a1 c1.u.x], null, java.lang.RuntimeException: Field state_ for c1.u not found. Known fields are [private int c1.u.v, private static final c1.u c1.u.w, private static volatile com.google.protobuf.a1 c1.u.x]
                 	at com.google.protobuf.v0.n0(Unknown Source:72)
                 	at com.google.protobuf.v0.T(Unknown Source:655)
                 	at com.google.protobuf.v0.R(Unknown Source:12)
                 	at com.google.protobuf.k0.e(Unknown Source:60)
                 	at com.google.protobuf.k0.a(Unknown Source:49)
                 	at com.google.protobuf.d1.d(Unknown Source:17)
                 	at com.google.protobuf.d1.e(Unknown Source:4)
                 	at com.google.protobuf.z.A(Unknown Source:4)
                 	at com.google.protobuf.z$a.y(Unknown Source:9)
                 	at com.google.protobuf.z$a.x(Unknown Source:0)
                 	at c1.l.onMethodCall(Unknown Source:1020)
                 	at ua.k$a.a(Unknown Source:17)
                 	at ha.c.l(Unknown Source:18)
                 	at ha.c.m(Unknown Source:40)
                 	at ha.c.i(Unknown Source:0)
                 	at ha.b.run(Unknown Source:12)
                 	at android.os.Handler.handleCallback(Handler.java:942)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:201)
                 	at android.os.Looper.loop(Looper.java:288)
                 	at android.app.ActivityThread.main(ActivityThread.java:7959)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
                 )
                 #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652)
                 #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310)
                 <asynchronous suspension>
                 #2      FlutterBluePlus.state (package:flutter_blue_plus/src/flutter_blue_plus.dart:98)
                 <asynchronous suspension>
```

I cannot try out newer versions yet because of another issue: https://github.com/boskokg/flutter_blue_plus/issues/409

But maybe I'll check if I'm able to try out newer versions and if the issue still persists. If it does, I'll update you here.

**Comment by chipweinberger** [comment]
Merged!

**Comment by shubhamsinghmutualmobile** [comment]
Thank you very much @chipweinberger 🤝 
You're awesome 🌟

**Pull request merged**
