### PR TITLE
Allow custom log handling (2)

### PR DESCRIPTION
**Pull request by benthillerkus**
This is just #830 but squashed & rebased to `master` and with most of the provided feedback addressed.
I didn't rename `setSendLogsToDart` to `setLogger` yet though, because even if my name was pretty clunky it was at least accurate to what's happening.

### CODE REVIEW

**Comment by chipweinberger** [comment]
using `setLogger` instead of `setSendLogsToDart` is because it is the matching native code for the `setLogger` call.

When you ctrl-f the code base for `setLogger`, you'll see all the code you need to see.

**Comment by chipweinberger** [comment]
this pr looks much nicer.

**Comment by chipweinberger** [comment]
* "[FBP] [%@]" please keep it as "[FBP-iOS]", "[FBP-macOS]"
* is there a reason you moved `case "setOptions":` and `case "setLogLevel":` higher up? or just cleaning things up
* the readme explanation for setLogger is *much* too long. this is a simple, optional feature. It should be very short in the readme.

**Comment by chipweinberger** [comment]
closing. would not merge it in this state. It should be a minimal implementation with minimal changes.

**Comment by benthillerkus** [comment]
I was gonna impl those changes, but I couldn't really find the time for it in the last 2 weeks

**Comment by chipweinberger** [comment]
no worries. If you get around to it, feel free to do it!

By habit, I close PRs & Issues that are not "active" for awhile, as often people drop off.

I do like the idea of the PR.

**Comment by chipweinberger** [comment]
I added this in 1.34.5

`FlutterBluePlus.logs`

**Pull request closed without merging**
