### PR TITLE
Merging multiple MSDs with the same manufacturer ID

### PR DESCRIPTION
**Pull request by MrCsabaToth**
Fixing https://github.com/boskokg/flutter_blue_plus/issues/785
1. Needed to change input parameters for proposed `getManufacturerSpecificData`
2. Also changed from `List<Integer>` to `byte[]`, because `getBytes` returns that, and in the other end `bytesToHex` requires that as well. So it's unnecessary weight lifting to to convert to List<Integer>. We just merge `byte[]` chunks with `System.arraycopy`.

### CODE REVIEW

**Comment by MrCsabaToth** [comment]
This is a proposal

**Comment by MrCsabaToth** [comment]
Note that I also made parts of the `getAppearanceFromScanRecord` function use the similar constructs as the newly introduced and proposed function.

**Comment by chipweinberger** [comment]
what api level is entrySet?

**Comment by chipweinberger** [comment]
I've reverted for now until we can verify iOS behavior

**Comment by MrCsabaToth** [comment]
Let's disregard my old iPad, @zwells confirmed that it's consistent on Android vs iOS, we'll possible be even more consistent on various devices than nRF!

**Pull request merged**
