### PR TITLE
fix: use `debugPrint` instead of `print` for logging information

### PR DESCRIPTION
**Pull request by dhruvanbhalara**
- fixes https://github.com/boskokg/flutter_blue_plus/issues/453

### CODE REVIEW

**Comment by MrCsabaToth** [comment]
That's a great find. It's also great that you are importing the foundations and not the cupertino (comes first choice in ABC as the possible choices besides foundations and material)

**Comment by dhruvanbhalara** [comment]
@MrCsabaToth @chipweinberger I've used `debugPrint` for reason, if app is overriding `debugPrint` as per application/developer requirements in that case configuration is applied to it. in other case if `print` is used that will be use own confirmation and it's visible in production build as well.

**Comment by chipweinberger** [comment]
@dhruvanbhalara , thanks for the PR. 

I've already pushed a fix for #453 

There is not need for `debugPrint` because logs can be turned off with `FlutterBluePlus.setLogLeve(LogLevel.none)`

**Comment by MrCsabaToth** [comment]
https://github.com/boskokg/flutter_blue_plus/commit/e53b1e1261064f6fc6063d3ec074a5dcbc740d98 looks like on `print` only from `write`. This PR modified 3 more places where there are (were?) `print`.

**Comment by chipweinberger** [comment]
we should keep those as 'print'. 

`debugPrint` can skip logs to increase perf, which is not what we want. To increase perf, users should set 
`setLogLevel`.

I know dart likes to complain about print, but there is no issue to fix. I've already disabled the warnings for that.

**Comment by MrCsabaToth** [comment]
As long as the `print` is not executed in release version then OK. I didn't know `debugPrint` can be skipped for performance, I'll read about that.

**Comment by benthillerkus** [comment]
> debugPrint can skip logs to increase perf, which is not what we want, because it hurts debugging.

AFAIK it's actually the opposite: [Android may drop lines with `print`, but throttles the log output with `debugPrint`, so that nothing is printed](https://arc.net/l/quote/bqutvrky).

**Pull request closed without merging**
