### PR TITLE
fix: uncatchable timeout exception in BluetoothDevice.connect

### PR DESCRIPTION
**Pull request by crazy-rodney**
#31

### CODE REVIEW

**Comment by boskokg** [comment]
Hello @crazy-rodney.
Thank you for the contribution on this plugin.

I am not sure about the proposed change since it covers the mentioned issue, but what I see it also brings the change in the currrent code where we had the connection timeout optional feature (turned off by default), and now it is the mandatory feature (with the default timeout set to 20s).

Second thing is that anyone can wrap the connect method and do the timeout processing the way it suits the needs, so I am not sure if we need this issue fixed at all.

Can you please give some feedback on this?

**Comment by sophisticode** [comment]
In my opinion, we should fix the timeout behaviour which does not work as intended (you cannot catch the exception within the app).

I propose to leave the timeout parameter optional and do something like this in the code: 

`      final connectFuture = Future(() async {
        var request = protos.ConnectRequest.create()
          ..remoteId = id.toString()
          ..androidAutoConnect = autoConnect;

        await FlutterBluePlus.instance._channel
            .invokeMethod('connect', request.writeToBuffer());

        await state.firstWhere((s) => s == BluetoothDeviceState.connected);
      });
      await (timeout != null ? connectFuture.timeout(timeout) : connectFuture);
`

**Comment by SkuggaEdward** [comment]
I was about to make a PR for the same problem. Tho slightly different mod.
https://github.com/SkuggaEdward/flutter_blue_plus/blob/21d7bae2bb0b2fa5ba39d2cce2ad3c4adeb973f8/lib/src/bluetooth_device.dart#L42-L49

**Comment by cthurston** [comment]
And one more way to solve it: https://github.com/Flowline/flutter_blue/pull/1/commits/de83c9ea06aabb9dbf5a85dbce760a659bbebf22

**Comment by crazy-rodney** [comment]
I currently do not have time to spend on this problem. I've been using my solution since I proposed it and its working fine for me. Maybe merge mine or one of @SkuggaEdward's or @cthurston's. I think it would benefit the project to address this issue.

**Comment by MousyBusiness** [comment]
```
Second thing is that anyone can wrap the connect method and do the timeout processing the way it suits the needs, so I am not sure if we need this issue fixed at all.
```

This is not true, you cannot catch the error as the timeout exception happens in a Timer handlers and doesn't propagate to the invoker. This is a major flutter_blue deficiency which has send me in search of a more active fork.

**Comment by SimonH-Zuma** [comment]
I concur with all the above. I've been pulling my hair out wondering why I cannot catch the timeout in order to set my 'connected' flag accordingly. This is a MAJOR issue/bug so I would be grateful if you can release this PR

**Comment by boskokg** [comment]
[SkuggaEdward](https://github.com/SkuggaEdward) proposal commited. closing merge request

**Pull request closed without merging**
