### PR TITLE
Fix for foreground isolate issue

### PR DESCRIPTION
**Pull request by ZainNomancowlar**
Fix for #198

### CODE REVIEW

**Comment by chipweinberger** [comment]
Can you describe the fix more? What are these lines doing?

**Comment by ZainNomancowlar** [comment]
I was having wierd issues when using the flutter blue plus with flutter_foreground_task plugin. for eg. If i started a bluetooth scan in the UI isolate, sometimes the scan results stream would get events in the foreground task but not in the UI isolate. I debugged things and found that two instances of the `FlutterBluePlusPlugin` class were being created. so i made some things static and made a map of method channels so that all data is sent to all isolates

**Comment by xbug42** [comment]
I did not test this PR but making things static will not help if you have one FlutterBluePlus instance in each isolate. Isolates do not share memory. It's like separate processes for memory...
@ZainNomancowlar : doing scans in multiple isolates sounds like a good way to have all kinds of troubles to me... I really think only one isolate should handle all the bluetooth things....

**Comment by ZainNomancowlar** [comment]
I havent got around to testing it much. I eventually decided to only use flutter blue plus in the foreground service. Plus i havent tested it at all in iOS. I think the changes might not be needed after all.

**Pull request closed without merging**
