### PR TITLE
Port macos support from flutter_blue

### PR DESCRIPTION
**Pull request by tuna-f1sh**
Ports https://github.com/pauldemarco/flutter_blue/pull/626, resolving #2 - remaining classes to reflect this library's naming.

macOS support worked great for me (Intel macOS 12.0) in https://github.com/boskokg/flutter_blue so it seems a shame to drop it.

I excluded the example since the macOS support is a side feature and the example seemed to create extra workload in the previous libraries.

### CODE REVIEW

**Comment by FXschwartz** [comment]
This is super exciting, thank you @tuna-f1sh for spending the time creating this PR!

**Comment by chipweinberger** [comment]
Thanks for the PR.

I see this port is based off the iOS code. 

The iOS code was recently reformatted here: https://github.com/boskokg/flutter_blue_plus/commit/0e879e4ca216ae1a017e39d97b9c93fd199b436d

And more functions added here:
https://github.com/boskokg/flutter_blue_plus/commit/88fb60daeb0d098f943098244123fedf8791bef4

If this PR is updated, I will merge it. Thanks.

**Comment by chipweinberger** [comment]
I also see that this PR adds requestConnectionPriority, which was recently added here: https://github.com/boskokg/flutter_blue_plus/commit/88fb60daeb0d098f943098244123fedf8791bef4

I will close this PR since it would require rework. Please reopen a PR with a minimal change if you want this feature merged.

**Comment by tuna-f1sh** [comment]
This referenced my master branch. I added the request phy2M and connection priority recently admittedly forgetting about this since 8 months had passed.

I can create a PR with just the macOS support from the old flutter_blue if it was just a clang format required?

Re: https://github.com/boskokg/flutter_blue_plus/commit/88fb60daeb0d098f943098244123fedf8791bef4 is there any chance of adding https://developer.android.com/reference/android/bluetooth/BluetoothGatt#setPreferredPhy(int, int, int) along with this? I found it's required to achieve high throughput BLE. I did it with a single method but could be done properly with the args like how you implemented requestConnectionPriority.

**Comment by chipweinberger** [comment]
yes if you open a PR for setPreferredPhy separately!

**Pull request closed without merging**
