### PR TITLE
L2cap merge

### PR DESCRIPTION
**Pull request by rehlma**
Update and merge L2Cap changes from https://github.com/continental/flutter_blue_plus/tree/master

See [L2Cap PR](https://github.com/boskokg/flutter_blue_plus/pull/836)

### CODE REVIEW

**Comment by chipweinberger** [comment]
"57 files changed"

this will never be merged. It is too big. 

I am the only maintainer of this package, and I can't maintain this code.

**Comment by chipweinberger** [comment]
I suggest you publish this as  a separate package

"fbp_l2cap" or something

**Comment by rehlma** [comment]
It wasn't my plan to open this PR, at least not in this state. I wanted to open the PR on my fork, but this repo was preselected. There were a few features missing.

I've read your comments and will try to move everything into one file. Since the actual code changes aren't that much, it's not a big deal to move the Java or Swift code. My problem is obj-c.

But you're right, although I would prefer to merge it at some point, we could also release a separate package.

**Comment by Plinzen** [comment]
Hello, 

I just saw your comment about the L2cap channels. I have basically implemented this PR and I'd appreciate if you get this on a separate project. I couldn't accomplish the open points because I can't write ObjC (and it's not necessary at all, IMHO) and I don't agree on a single file architecture. However, if you want to create a separate library, I'd be very happy and I can support up to a certain limit. We didn't follow up here, as the app which used the l2cap channels was retired.

**Comment by rehlma** [comment]
Hey, I'm still planning on making a separate plugin for L2cap, but I'm a bit short on time. Our fork works fine so far, but it's not on the latest commit. I'll post it as soon the first version is ready to test 👍

**Pull request closed without merging**
