### PR TITLE
feat : add get bytes

### PR DESCRIPTION
**Pull request by shbae-musma**
get bytes 구현

### CODE REVIEW

**Comment by chipweinberger** [comment]
this will not work on iOS. Therefore, I do not want to add it.

Why do you need it?

**Comment by shbae-musma** [comment]
I will make sure to modify the iOS source code later. Thank you very much.

**Comment by chipweinberger** [comment]
iOS does not allow raw bytes.

It cannot be supported on iOS.

**Comment by shbae-musma** [comment]
Wow, I didn't know that, thank you for letting me know!

**Pull request closed without merging**
