### PR TITLE
iOS Peripheral not found issue fixed

### PR DESCRIPTION
**Pull request by keskink**
Now, you can connect without scan on iOS as well.

### CODE REVIEW

**Comment by chipweinberger** [comment]
Thanks.

why are you using a new class variable fxPeripheral? 

you could just set the already existing "peripheral" variable.

**Comment by keskink** [comment]
Please change the line as 
@property(nonatomic, **retain**) CBPeripheral *fxPeripheral;

I am not swift expert. But as far as I know @property making fxPperipheral as global in CBCentralManager instance.

**Comment by keskink** [comment]
> 

Yes Ia m aldeady using.

**Comment by keskink** [comment]
ok. Explaning what I do.
The sources in git, 1.6.1 version. I cloned and changed in FlutterBluePlusPlugin.m.
But I had some problem as well.
There is 1.5.2 version on pub.dev. I am using 1.5.2 version from pub.dev. And I cloned sources from /Users/../.pub-cache/hosted/pub.dev/flutter_blue_plus-1.5.2
and made changes. 
Now I am using modified 1.5.2. 
I put Pull Request for owner of this plugin. May be he can use my codes in oficial 1.6.1 version.

**Comment by WeiKuang** [comment]
image

**Pull request closed without merging**
