### PR TITLE
Adding support for BLE Appearance type

### LINKED ISSUE #202: [Feature]: Support Appearance values
There are Categories and Subcategories defined here 
[Appearance Values.pdf](https://github.com/boskokg/flutter_blue_plus/files/10681601/Appearance.Values.pdf)

In some cases it's not enough to see what services a device exposes to exactly identify them. For example FTMS Fitness Machines hint their types (Indoor Bike, Treadmill, Rower, ...) via advertisement service data.

However in case of CSC (Cycling Speed and Cadence Sensors) there's no such service data, but I could tell apart speed and cadence sensors by looking at the appearance. That would hint the type. I saw that nRF Connect can sense that appearance without connecting to a device and polling the characteristics.

Bellow is an nRF scan, this time with a HRM:
Screenshot_2023-02-07-20-29-46-77_3c2e989be58abe9ca7463ffb1e6967d2

### LINKED ISSUE #766: [Feature]: Support Appearance values
### FlutterBluePlus Version

1.31.8

### Flutter Version

3.19.0-0.1.pre

### What OS?

Android

### OS Version

12, 13

### Bluetooth Module

.

### What is your feature request?

Appearance type is a Bluetooth LE standard feature.

Many applications have to deal with various types of BLE devices. One way to identify them is to look at the service data in the advertisement. However that is often vague, and it's even advised to first look at the Appearance data, especially when multiple services mentioned in the services list (see https://stackoverflow.com/a/44292698/292502 where it's a Herta Rate Sensor + a Running Cadence and Speed Sensor).

It's extremely costly (and kind of infeasible) to connect to devices just to categorize them. This is why somewhat surprising that iOS is not supporting this standard (#202), however there are already multiple features which iOS holds back but the Android side of FBP supports. This would be another one, and the PR IMHO is not an invasive change.

### Logs

```shell
.
```

### PR DESCRIPTION
**Pull request by MrCsabaToth**
Currently for Android. Fixes #766 and fixes #202

### CODE REVIEW

**Comment by MrCsabaToth** [comment]
Hold up! There should be only 3 file changes. Somehow the fork is behind. The fork sync on GitHub doesn't seem to indicate that it's behind though. I'll fix it.

**Comment by chipweinberger** [comment]
also please add comments saying this is android only to the api =)

**Comment by MrCsabaToth** [comment]
I realized, probably that's why Bard was hallucinating and haven't found examples. The code worked though on Android 13. I'll rewrite and retest on Android 12, 13, 9 and 6.

**Comment by MrCsabaToth** [comment]
I made some comments and implementation for API level 21+ to Android 13. I tested Android 6, 9, 12, and 13. iOS supposed to work (of course without supplying this data), since when the appearance is missing it's not added to the map (which travels up to the Dart layer) on Android either, and that's how it would always be on an iOS device.

**Comment by MrCsabaToth** [comment]
Let me know if any more changes needed

**Comment by chipweinberger** [comment]
looks pretty good! thanks for your work @MrCsabaToth !

a few small things
- rebase into a single commit
- "// BLE standard, but Android only" I'd "Android Only" for brevity
- move this code into its own function 
```
        // Appearance Type
        int appearance = 0;
        if (adv != null) {
           ........
        }
```

**Comment by MrCsabaToth** [comment]
I made the changes:
1. Comment modification
2. Extracting the function to getAppearanceFromScanRecord
3. Squashing the commits into [1f2c0b394650095fd3bd12240e6abba8da9e0456](https://github.com/CsabaConsulting/flutter_blue_plus/commit/1f2c0b394650095fd3bd12240e6abba8da9e0456)

**Comment by chipweinberger** [comment]
the PR still says 18 commits

**Comment by MrCsabaToth** [comment]
I see, not sure why. Next time I'll use `git town hack` / `git town ship` and that squashes automatically. Normally I use git flow. I'll figure out something.

**Comment by chipweinberger** [comment]
use git log, git reset XXXX --soft, git commit

**Comment by MrCsabaToth** [comment]
Hmmm, I did a regular push with a merge. I guess I need the force

**Comment by MrCsabaToth** [comment]
Git can be extremely frustrating, it's squashed now but somehow one commit is in there (an extra file).

**Comment by chipweinberger** [comment]
use git command line, not UI.

**Pull request closed without merging**
