### PR TITLE
Adding windows

### PR DESCRIPTION
**Pull request by jurapusic**
I added windows part of  flutter_blue_plugin into flutter_blue_plus.
I need to test it.

### CODE REVIEW

**Comment by chipweinberger** [comment]
awesome!

please read this issue: https://github.com/boskokg/flutter_blue_plus/issues/6#issuecomment-1932546607

You should make a new pub.dev project. I will link to it in my readme.

**Comment by jurapusic** [comment]
Hello
I am very sorry.
I really didn't think my account would be blocked due to any reason.
In fact, I and my son have been using this account together until now
Even if he is my son, English sentence pattern can't be same each other.
So it seems that this account was blocked
When we took a contract, I thought we will create successful and great working relation ship each other continuously in the future.
But unfortunately, we cann't even have a connection with each other due to account block.
Currently I have already updated first version in git and am completing it one by one.

My gmail is marijanpusic66@gmail.com
My son's gmail is jurapusic056@gmail.com
Skype ID : live:.cid.bb89b1ac7906c22

I would be appreciated it if you send me message related with your project throgh these emials.

Or you can give your phone number
I allowed your refund request.
To be honest, I feel very sad that I worked on your project for almost 1 week.
And I already did windows plugin.
I would be appreciated if you reach out to me by my email
Thanks

**Comment by chipweinberger** [comment]
i don't understand. blocked where?

**Comment by chipweinberger** [comment]
ah okay. So you are leaving this message here for them to read

**Comment by jurapusic** [comment]
Yes
Could you please communicate with me through email or skype?
I am waiting for your respond.

**Comment by jurapusic** [comment]
Hello
I would be appreciated it if you reached to me through email or Skype.
Thanks

**Comment by jurapusic** [comment]
Hello
I wish I had connected with you for completing project.
I am looking forward to your respond.
Thanks.

**Comment by jurapusic** [comment]
Hello.
Please tell me your opinions.
Thanks.

**Comment by Shunt22** [comment]
@jurapusic 
It would be great to have windows implementation of this package!
Any chance you can upload your realisation as separete pub dev package or a flutter_blue_plus fork?

**Comment by chipweinberger** [comment]
you can already use it:

**pubspecl.yaml**
```
dependencies:
  flutter_blue_plus:
    git:
      url: https://github.com/HumanComputingInc/flutter_blue_plus.git
      ref: master
```

warning: it's probably very buggy.

**Comment by chipweinberger** [comment]
closing because the code looks copy pasted and incorrect.

**Pull request closed without merging**
