### PR TITLE
Android: Relaxed scanning permission requirements

### LINKED ISSUE #280: Android: Permission requirements for BLE scanning on Android 12+ are too pedantic
The permission checks before BLE scanning on Android 12+ are too pedantic/aggressive.

[This check](https://github.com/boskokg/flutter_blue_plus/blob/d562274902f1d0bdc7f08b9e42f2d1452380063d/android/src/main/java/com/boskokg/flutter_blue_plus/FlutterBluePlusPlugin.java#LL272C28-L272C28) checks for fine location before attempting to scan. This check is incorrect.

According to the [Android specification](https://developer.android.com/reference/android/bluetooth/le/BluetoothLeScanner#startScan(java.util.List%3Candroid.bluetooth.le.ScanFilter%3E,%20android.bluetooth.le.ScanSettings,%20android.app.PendingIntent)), fine location is not required when `usesPermissionFlags="neverForLocation"` is specified in the app manifest.

### PR DESCRIPTION
**Pull request by virshe00**
Resolves #280

### CODE REVIEW

**Comment by virshe00** [comment]
This change is untested! I haven't had time to do any testing. If someone could please pull this branch and try it out, that would be useful.

**Comment by chipweinberger** [comment]
let me know when it is tested.

**Comment by virshe00** [comment]
Yeah I might get around to it, but if anyone would like to see it merged sooner, testing it would help a lot.

**Comment by virshe00** [comment]
Still requests fine location in the app. I'll need to fix this as well as test in my own app.

**Comment by virshe00** [comment]
I rebased master on top of my branch. I seem to have issues trying to scan to devices, I'll need to spend some more time on it.

**Comment by bruce3x** [comment]
I think you should make changes based on release 1.6.1(https://github.com/boskokg/flutter_blue_plus/commit/928fecb985892daa6f5c87c2069d8057e7c452ab), because the master branch is removing protobuf and is currently not in a usable state. 😅

**Comment by chipweinberger** [comment]
This should now be fixed

https://github.com/boskokg/flutter_blue_plus/commit/8a35c6a0b6aca2fe23e5cd3730b7d3cf7903437c
https://github.com/boskokg/flutter_blue_plus/commit/c0b1de652b141a5962477b48d6cd6de757fa36f0

**Pull request closed without merging**
